image: alpine:latest  # Set the base image to Alpine Linux

variables:
  AUTO_BUILD_IMAGE_VERSION: 'v4.3.0'  # Define the build image version
  DOCKER_HOST: tcp://0.0.0.0:2375  # Docker daemon address
  DOCKER_DRIVER: overlay2  # Docker storage driver
  DOCKER_TLS_CERTDIR: ''  # Disable TLS for Docker
  CI_APPLICATION_TAG: $CI_COMMIT_SHORT_SHA  # Use the commit short SHA as Docker image tag
  VITE_BACKEND_HOST: '35.228.179.101'  # Default value for VITE_BACKEND_HOST

stages:
  - build  # Build stage
  # - test  # Uncomment this line if you have a test stage
  - deploy  # Deploy stage

build-job:
  stage: build  # Define the build job under the build stage
  image: '${CI_TEMPLATE_REGISTRY_HOST}/gitlab-org/cluster-integration/auto-build-image:${AUTO_BUILD_IMAGE_VERSION}'  # Use a pre-configured build image
  services:
    - name: 'docker:20.10.12-dind'  # Use Docker-in-Docker service
      command: ['--tls=false', '--host=tcp://0.0.0.0:2375']  # Docker daemon options
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY  # Log in to the Docker registry    
  script:
    - |
      # Set the repository and tag for the Docker image based on the commit info
      if [[ -z "$CI_COMMIT_TAG" ]]; then
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG}
        export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_SHORT_SHA}
      else
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE}
        export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_TAG}
      fi
    - /build/build.sh  # Run the build script
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Run on default branch
    - if: $CI_COMMIT_BRANCH == "feat-ci"  # Run on feat-ci branch
  artifacts:
    reports:
      dotenv: gl-auto-build-variables.env  # Store environment variables for later jobs

# test-job:
#   TODO  # Define a test job if needed

deploy-job:
  stage: deploy  # Define the deploy job under the deploy stage
  image: 'alpine:latest'  # Use Alpine Linux image for deployment
  before_script:
    - apk add --no-cache curl bash  # Install curl and bash
    - curl -sL https://helm.sh/install | bash  # Install Helm
  script: # Use Helm to deploy the frontend
    - |
      helm upgrade --install scalyshop-frontend ./scalyshop-frontend \
        --set image.repository=$CI_REGISTRY_IMAGE \
        --set image.tag=$CI_APPLICATION_TAG \
        --namespace scalyshop
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Run on default branch
    - if: $CI_COMMIT_BRANCH == "feat-ci"  # Run on feat-ci branch
  when: on_success  # Only run if previous jobs succeed
