apiVersion: v1
kind: Service
metadata:
  name: scalyshop-v2-frontend-service
  labels:
    app: ss-frontend
spec:
  type: LoadBalancer
  selector:
    app: ss-frontend
  ports:
    - port: 80
      targetPort: 5046